### ISSUE TITLE
Daily Scroll Preparation (Scroll Adept) Not Working

### ISSUE THREAD

**Issue by dogstarrb** [reonZ/pf2e-dailies#34]
When trying to make daily preparations, the slots for the spells to be made into scrolls are unable to receive spell input. This seems to be because of it using "PF2E.SpellLevelX" which has likely been changed over to "PF2E.SpellRankX" in light of the remaster wording changes.
![Scroll Adept](https://github.com/reonZ/pf2e-dailies/assets/7331744/d6ff1179-6ad3-4a03-9c0c-0d37cbc8eb09)

**Comment by zacdemon** [comment]
Also running into this issue with scroll esoterica. Console generates the below error.

<html>
<body>
<div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; color: rgb(255, 255, 255); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div tabindex="-1" class="console-message-wrapper console-error-level console-selected" role="log" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); --console-color-lightmagenta: rgb(214 112 214);"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="shared.js:25  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'selected')
    at checkFilter (shared.js:25:14)
    at parseSpellFilter (shared.js:62:24)
    at async se.parseFilter (shared.js:15:17) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://52.70.55.33:30000/modules/pf2e-dailies/src/apps/interface/shared.js:25" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">shared.js:25</span> <devtools-icon class="resource-links" title="Search for this message on the Web" role="button" tabindex="0" style="display: inline-block; white-space: nowrap; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-top: -1px; margin-bottom: -4px; cursor: pointer;"><div class="icon-basic" style="width: 16px; height: 16px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/Images/edge-search-info.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--color-link));"></div></devtools-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot set properties of undefined (setting 'selected')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at checkFilter (<span class="devtools-link" role="link" tabindex="-1" title="http://52.70.55.33:30000/modules/pf2e-dailies/src/apps/interface/shared.js:25:14" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">shared.js:25:14</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at parseSpellFilter (<span class="devtools-link" role="link" tabindex="-1" title="http://52.70.55.33:30000/modules/pf2e-dailies/src/apps/interface/shared.js:62:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">shared.js:62:24</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async se.parseFilter (<span class="devtools-link" role="link" tabindex="-1" title="http://52.70.55.33:30000/modules/pf2e-dailies/src/apps/interface/shared.js:15:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">shared.js:15:17</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | checkFilter | @ | shared.js:25
-- | -- | -- | --
  | parseSpellFilter | @ | shared.js:62
  | await in parseSpellFilter (async) |   |  
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

</span></div></div></div></div></div></div><div aria-hidden="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 0px; color: transparent;">﻿</div>
</body>
</html>

**Comment by reonZ** [comment]
this should be fixed with the `2.14.0` version
